# The main clocks are all autogenerated by the Xilinx IP
# clk_out3_xlnx_mmcm is the 20Mhz clock from the mmcm used to drive wally and the AHB Bus.
# mmcm_clkout0 is the clock output of the DDR3 memory interface / 4.
# This clock is not used by wally or the AHB Bus. However it is used by the AXI BUS on the DD3 IP.

#create_generated_clock -name CLKDiv64_Gen -source [get_pins wallypipelinedsoc/uncore.uncore/sdc.SDC/sd_top/slow_clk_divider/clkMux/I0] -multiply_by 1 -divide_by 1 [get_pins wallypipelinedsoc/uncore.uncore/sdc.SDC/sd_top/slow_clk_divider/clkMux/O]
create_generated_clock -name SPISDCClock -source [get_pins mmcm/clk_out3] -multiply_by 1 -divide_by 1 [get_pins wallypipelinedsoc/SPICLK]

##### clock #####
set_property PACKAGE_PIN AD12 [get_ports default_200mhz_clk_p]
set_property PACKAGE_PIN AD11 [get_ports default_200mhz_clk_n]
set_property IOSTANDARD LVDS [get_ports default_200mhz_clk_p]

# *** don't love this hack.  RT: Don't understand why the recomemded input clock is causing a clock routing issue.
set_property CLOCK_DEDICATED_ROUTE BACKBONE [get_nets default_200mhz_clk_p]
set_property CLOCK_DEDICATED_ROUTE BACKBONE [get_nets default_200mhz_clk_n]

# ##### RVVI Ethernet ####
# # taken from https://github.com/Digilent/digilent-xdc/blob/master/Genesys-2-Master.xdc
# set_property -dict { PACKAGE_PIN AH11  IOSTANDARD LVCMOS15 } [get_ports { phy_rxctl }]; #IO_L18P_T2_33 Sch=eth_rx_ctl
# set_property -dict { PACKAGE_PIN AG10  IOSTANDARD LVCMOS15 } [get_ports { phy_rx_clk }]; #IO_L13P_T2_MRCC_33 Sch=eth_rx_clk
# set_property -dict { PACKAGE_PIN AJ14  IOSTANDARD LVCMOS15 } [get_ports { phy_rxd[0] }]; #IO_L21N_T3_DQS_33 Sch=eth_rx_d[0]
# set_property -dict { PACKAGE_PIN AH14  IOSTANDARD LVCMOS15 } [get_ports { phy_rxd[1] }]; #IO_L21P_T3_DQS_33 Sch=eth_rx_d[1]
# set_property -dict { PACKAGE_PIN AK13  IOSTANDARD LVCMOS15 } [get_ports { phy_rxd[2] }]; #IO_L20N_T3_33 Sch=eth_rx_d[2]
# set_property -dict { PACKAGE_PIN AJ13  IOSTANDARD LVCMOS15 } [get_ports { phy_rxd[3] }]; #IO_L22P_T3_33 Sch=eth_rx_d[3]
# set_property -dict { PACKAGE_PIN AE10  IOSTANDARD LVCMOS15 } [get_ports { phy_tx_clk }]; #IO_L14P_T2_SRCC_33 Sch=eth_tx_clk
# set_property -dict { PACKAGE_PIN AK14  IOSTANDARD LVCMOS15 } [get_ports { phy_tx_en }]; #IO_L20P_T3_33 Sch=eth_tx_en
# set_property -dict { PACKAGE_PIN AJ12  IOSTANDARD LVCMOS15 } [get_ports { phy_txd[0] }]; #IO_L22N_T3_33 Sch=eth_tx_d[0]
# set_property -dict { PACKAGE_PIN AK11  IOSTANDARD LVCMOS15 } [get_ports { phy_txd[1] }]; #IO_L17P_T2_33 Sch=eth_tx_d[1]
# set_property -dict { PACKAGE_PIN AJ11  IOSTANDARD LVCMOS15 } [get_ports { phy_txd[2] }]; #IO_L18N_T2_33 Sch=eth_tx_d[2]
# set_property -dict { PACKAGE_PIN AK10  IOSTANDARD LVCMOS15 } [get_ports { phy_txd[3] }]; #IO_L17N_T2_33 Sch=eth_tx_d[3]
# # have to update these in the future. Follow the rvviopt branch from the vcu108 config.
# #set_property -dict { PACKAGE_PIN AK16  IOSTANDARD LVCMOS18 } [get_ports { eth_int_b }]; #IO_L1P_T0_32 Sch=eth_intb
# #set_property -dict { PACKAGE_PIN AF12  IOSTANDARD LVCMOS15 } [get_ports { eth_mdc }]; #IO_L23P_T3_33 Sch=eth_mdc
# #set_property -dict { PACKAGE_PIN AG12  IOSTANDARD LVCMOS15 } [get_ports { eth_mdio }]; #IO_L23N_T3_33 Sch=eth_mdio
# #set_property -dict { PACKAGE_PIN AH24  IOSTANDARD LVCMOS33 } [get_ports { ETH_PHYRST_N }]; #IO_L14N_T2_SRCC_12 Sch=eth_phyrst_n
# #set_property -dict { PACKAGE_PIN AK15  IOSTANDARD LVCMOS18 } [get_ports { eth_pme_b }]; #IO_L1N_T0_32 Sch=eth_pmeb

##### GPI ####
set_property -dict { PACKAGE_PIN E18   IOSTANDARD LVCMOS12 } [get_ports { GPI[0] }]; #IO_25_17 Sch=btnc
set_property -dict { PACKAGE_PIN M19   IOSTANDARD LVCMOS12 } [get_ports { GPI[1] }]; #IO_0_15 Sch=btnd
set_property -dict { PACKAGE_PIN M20   IOSTANDARD LVCMOS12 } [get_ports { GPI[2] }]; #IO_L6P_T0_15 Sch=btnl
set_property -dict { PACKAGE_PIN C19   IOSTANDARD LVCMOS12 } [get_ports { GPI[3] }]; #IO_L24P_T3_17 Sch=btnr
set_input_delay -clock [get_clocks clk_out3_mmcm] -min -add_delay 0.000 [get_ports {GPI[*]}]
set_input_delay -clock [get_clocks clk_out3_mmcm] -max -add_delay 0.000 [get_ports {GPI[*]}]
set_max_delay -from [get_ports {GPI[*]}] 20.000


##### GPO ####
set_property -dict { PACKAGE_PIN T28   IOSTANDARD LVCMOS33 } [get_ports { GPO[0] }]; #IO_L11N_T1_SRCC_14 Sch=led[0]
set_property -dict { PACKAGE_PIN V19   IOSTANDARD LVCMOS33 } [get_ports { GPO[1] }]; #IO_L19P_T3_A10_D26_14 Sch=led[1]
set_property -dict { PACKAGE_PIN U30   IOSTANDARD LVCMOS33 } [get_ports { GPO[2] }]; #IO_L15N_T2_DQS_DOUT_CSO_B_14 Sch=led[2]
set_property -dict { PACKAGE_PIN U29   IOSTANDARD LVCMOS33 } [get_ports { GPO[3] }]; #IO_L15P_T2_DQS_RDWR_B_14 Sch=led[3]
set_property -dict { PACKAGE_PIN V20   IOSTANDARD LVCMOS33 } [get_ports { GPO[4] }]; #IO_L19N_T3_A09_D25_VREF_14 Sch=led[4]
set_max_delay -to [get_ports {GPO[*]}] 20.000

set_output_delay -clock [get_clocks clk_out3_mmcm] -min -add_delay 0.000 [get_ports {GPO[*]}]
set_output_delay -clock [get_clocks clk_out3_mmcm] -max -add_delay 0.000 [get_ports {GPO[*]}]



##### UART #####
# *** IOSTANDARD is probably wrong
set_property -dict { PACKAGE_PIN Y23   IOSTANDARD LVCMOS33 } [get_ports { UARTSout }]; #IO_L1P_T0_12 Sch=uart_rx_out
set_property -dict { PACKAGE_PIN Y20   IOSTANDARD LVCMOS33 } [get_ports { UARTSin }]; #IO_0_12 Sch=uart_tx_in
#set_property DRIVE 4 [get_ports UARTSout]
set_input_delay -clock [get_clocks clk_out3_mmcm] -min -add_delay 0.000 [get_ports UARTSin]
set_input_delay -clock [get_clocks clk_out3_mmcm] -max -add_delay 0.000 [get_ports UARTSin]
set_output_delay -clock [get_clocks clk_out3_mmcm] -min -add_delay 0.000 [get_ports UARTSout]
set_output_delay -clock [get_clocks clk_out3_mmcm] -max -add_delay 0.000 [get_ports UARTSout]


##### reset #####
#************** reset is inverted
set_property -dict { PACKAGE_PIN B19   IOSTANDARD LVCMOS12 } [get_ports { south_reset }]; #IO_L24N_T3_17 Sch=btnu
set_property -dict { PACKAGE_PIN R19   IOSTANDARD LVCMOS33 } [get_ports { resetn }]; #IO_0_14 Sch=cpu_resetn

set_input_delay -clock [get_clocks clk_out3_mmcm] -min -add_delay 2.000 [get_ports resetn]
set_input_delay -clock [get_clocks clk_out3_mmcm] -max -add_delay 2.000 [get_ports resetn]
set_max_delay -from [get_ports resetn] 20.000
set_false_path -from [get_ports resetn]


set_input_delay -clock [get_clocks clk_out3_mmcm] -min -add_delay 2.000 [get_ports south_reset]
set_input_delay -clock [get_clocks clk_out3_mmcm] -max -add_delay 2.000 [get_ports south_reset]
set_max_delay -from [get_ports south_reset] 20.000
set_false_path -from [get_ports south_reset]



##### SD Card I/O #####
#***** may have to switch to Pmod JB or JC.

# SDCDat[3]
set_property PACKAGE_PIN V27 [get_ports SDCCS]
set_property IOSTANDARD LVCMOS33 [get_ports SDCCS]
set_property PULLTYPE PULLUP [get_ports SDCCS]
# set_property -dict {PACKAGE_PIN Y26 IOSTANDARD LVCMOS33 PULLUP true} [get_ports {SDCDat[2]}]
# set_property -dict {PACKAGE_PIN U24 IOSTANDARD LVCMOS33 PULLUP true} [get_ports {SDCDat[1]}]
# SDCDat[0]
set_property PACKAGE_PIN V24 [get_ports SDCIn]
set_property IOSTANDARD LVCMOS33 [get_ports SDCIn]
set_property PULLTYPE PULLUP [get_ports SDCIn]
set_property PACKAGE_PIN W22 [get_ports SDCCLK]
set_property IOSTANDARD LVCMOS33 [get_ports SDCCLK]
set_property PULLTYPE PULLUP [get_ports SDCCLK]
set_property PACKAGE_PIN Y30 [get_ports SDCCmd]
set_property IOSTANDARD LVCMOS33 [get_ports SDCCmd]
set_property PULLTYPE PULLUP [get_ports SDCCmd]
set_property PACKAGE_PIN V22 [get_ports SDCCD]
set_property IOSTANDARD LVCMOS33 [get_ports SDCCD]
set_property PULLTYPE PULLUP [get_ports SDCCD]
set_property PACKAGE_PIN W21 [get_ports SDCWP]
set_property IOSTANDARD LVCMOS33 [get_ports SDCWP]
set_property PULLTYPE PULLUP [get_ports SDCWP]


set_output_delay -clock [get_clocks SPISDCClock] -min -add_delay 2.500 [get_ports {SDCCS}]
set_output_delay -clock [get_clocks SPISDCClock] -max -add_delay 10.000 [get_ports {SDCCS}]

set_input_delay -clock [get_clocks SPISDCClock] -min -add_delay 2.500 [get_ports {SDCIn}]
set_input_delay -clock [get_clocks SPISDCClock] -max -add_delay 10.000 [get_ports {SDCIn}]

set_output_delay -clock [get_clocks SPISDCClock] -min -add_delay 2.000 [get_ports {SDCCmd}]
set_output_delay -clock [get_clocks SPISDCClock] -max -add_delay 6.000 [get_ports {SDCCmd}]

set_output_delay -clock [get_clocks SPISDCClock] 0.000 [get_ports SDCCLK]


# SDHCI onboard microSD connector I/Os
set_property -dict { PACKAGE_PIN P28   IOSTANDARD LVCMOS33 PULLTYPE PULLUP } [get_ports { SD_CD_N }];   #IO_L8N_T1_D12_14 Sch=sd_cd
set_property -dict { PACKAGE_PIN R29   IOSTANDARD LVCMOS33 PULLTYPE PULLUP } [get_ports { SD_CMD }];    #IO_L7N_T1_D10_14 Sch=sd_cmd
set_property -dict { PACKAGE_PIN R26   IOSTANDARD LVCMOS33 PULLTYPE PULLUP } [get_ports { SD_DAT[0] }]; #IO_L10N_T1_D15_14 Sch=sd_dat[0]
set_property -dict { PACKAGE_PIN R30   IOSTANDARD LVCMOS33 PULLTYPE PULLUP } [get_ports { SD_DAT[1] }]; #IO_L9P_T1_DQS_14 Sch=sd_dat[1]
set_property -dict { PACKAGE_PIN P29   IOSTANDARD LVCMOS33 PULLTYPE PULLUP } [get_ports { SD_DAT[2] }]; #IO_L7P_T1_D09_14 Sch=sd_dat[2]
set_property -dict { PACKAGE_PIN T30   IOSTANDARD LVCMOS33 PULLTYPE PULLUP } [get_ports { SD_DAT[3] }]; #IO_L9N_T1_DQS_D13_14 Sch=sd_dat[3]
set_property -dict { PACKAGE_PIN R28   IOSTANDARD LVCMOS33 } [get_ports { SD_CLK }];                    #IO_L11P_T1_SRCC_14 Sch=sd_sclk



# *********************************
#set_property DCI_CASCADE {64} [get_iobanks 65]
#set_property INTERNAL_VREF 0.9 [get_iobanks 65]

# ddr3

set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[0]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[1]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[2]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[3]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[4]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[5]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[6]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[7]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[8]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[9]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[10]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[11]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[12]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[13]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[14]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[15]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[15]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[16]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[17]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[18]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[19]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[20]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[21]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[22]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[23]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[24]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[25]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[26]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[27]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[28]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[29]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[30]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[31]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dm[0]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dm[1]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dm[2]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dm[3]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports ddr3_dqs_p[0]]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports ddr3_dqs_n[0]]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports ddr3_dqs_p[1]]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports ddr3_dqs_n[1]]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports ddr3_dqs_p[2]]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports ddr3_dqs_n[2]]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports ddr3_dqs_p[3]]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports ddr3_dqs_n[3]]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[14]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[13]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[12]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[11]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[10]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[9]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[8]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[7]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[6]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[5]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[4]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[3]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[2]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[1]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[0]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_ba[2]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_ba[1]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_ba[0]}]
set_property IOSTANDARD DIFF_SSTL15_DCI [get_ports ddr3_ck_p[0]]
set_property IOSTANDARD DIFF_SSTL15_DCI [get_ports ddr3_ck_n[0]]
set_property IOSTANDARD SSTL15 [get_ports ddr3_ras_n]
set_property IOSTANDARD SSTL15 [get_ports ddr3_cas_n]
set_property IOSTANDARD SSTL15 [get_ports ddr3_we_n]
set_property IOSTANDARD SSTL15 [get_ports ddr3_reset_n]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_cke[0]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_odt[0]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_cs_n[0]}]

set_property PACKAGE_PIN AC12 [get_ports ddr3_addr[0]]
set_property PACKAGE_PIN AB8 [get_ports ddr3_addr[10]]
set_property PACKAGE_PIN AA8 [get_ports ddr3_addr[11]]
set_property PACKAGE_PIN AB12 [get_ports ddr3_addr[12]]
set_property PACKAGE_PIN AA12 [get_ports ddr3_addr[13]]
set_property PACKAGE_PIN AH9 [get_ports ddr3_addr[14]]
set_property PACKAGE_PIN AE8 [get_ports ddr3_addr[1]]
set_property PACKAGE_PIN AD8 [get_ports ddr3_addr[2]]
set_property PACKAGE_PIN AC10 [get_ports ddr3_addr[3]]
set_property PACKAGE_PIN AD9 [get_ports ddr3_addr[4]]
set_property PACKAGE_PIN AA13 [get_ports ddr3_addr[5]]
set_property PACKAGE_PIN AA10 [get_ports ddr3_addr[6]]
set_property PACKAGE_PIN AA11 [get_ports ddr3_addr[7]]
set_property PACKAGE_PIN Y10 [get_ports ddr3_addr[8]]
set_property PACKAGE_PIN Y11 [get_ports ddr3_addr[9]]
set_property PACKAGE_PIN AE9 [get_ports ddr3_ba[0]]
set_property PACKAGE_PIN AB10 [get_ports ddr3_ba[1]]
set_property PACKAGE_PIN AC11 [get_ports ddr3_ba[2]]
set_property PACKAGE_PIN AF11 [get_ports ddr3_cas_n]
set_property PACKAGE_PIN AC9 [get_ports ddr3_ck_n[0]]
set_property PACKAGE_PIN AB9 [get_ports ddr3_ck_p[0]]
set_property PACKAGE_PIN AJ9 [get_ports ddr3_cke[0]]
set_property PACKAGE_PIN AH12 [get_ports ddr3_cs_n[0]]
set_property PACKAGE_PIN AD4 [get_ports ddr3_dm[0]]
set_property PACKAGE_PIN AF3 [get_ports ddr3_dm[1]]
set_property PACKAGE_PIN AH4 [get_ports ddr3_dm[2]]
set_property PACKAGE_PIN AF8 [get_ports ddr3_dm[3]]
set_property PACKAGE_PIN AD3 [get_ports ddr3_dq[0]]
set_property PACKAGE_PIN AF1 [get_ports ddr3_dq[10]]
set_property PACKAGE_PIN AE4 [get_ports ddr3_dq[11]]
set_property PACKAGE_PIN AE3 [get_ports ddr3_dq[12]]
set_property PACKAGE_PIN AE5 [get_ports ddr3_dq[13]]
set_property PACKAGE_PIN AF5 [get_ports ddr3_dq[14]]
set_property PACKAGE_PIN AF6 [get_ports ddr3_dq[15]]
set_property PACKAGE_PIN AJ4 [get_ports ddr3_dq[16]]
set_property PACKAGE_PIN AH6 [get_ports ddr3_dq[17]]
set_property PACKAGE_PIN AH5 [get_ports ddr3_dq[18]]
set_property PACKAGE_PIN AH2 [get_ports ddr3_dq[19]]
set_property PACKAGE_PIN AC2 [get_ports ddr3_dq[1]]
set_property PACKAGE_PIN AJ2 [get_ports ddr3_dq[20]]
set_property PACKAGE_PIN AJ1 [get_ports ddr3_dq[21]]
set_property PACKAGE_PIN AK1 [get_ports ddr3_dq[22]]
set_property PACKAGE_PIN AJ3 [get_ports ddr3_dq[23]]
set_property PACKAGE_PIN AF7 [get_ports ddr3_dq[24]]
set_property PACKAGE_PIN AG7 [get_ports ddr3_dq[25]]
set_property PACKAGE_PIN AJ6 [get_ports ddr3_dq[26]]
set_property PACKAGE_PIN AK6 [get_ports ddr3_dq[27]]
set_property PACKAGE_PIN AJ8 [get_ports ddr3_dq[28]]
set_property PACKAGE_PIN AK8 [get_ports ddr3_dq[29]]
set_property PACKAGE_PIN AC1 [get_ports ddr3_dq[2]]
set_property PACKAGE_PIN AK5 [get_ports ddr3_dq[30]]
set_property PACKAGE_PIN AK4 [get_ports ddr3_dq[31]]
set_property PACKAGE_PIN AC5 [get_ports ddr3_dq[3]]
set_property PACKAGE_PIN AC4 [get_ports ddr3_dq[4]]
set_property PACKAGE_PIN AD6 [get_ports ddr3_dq[5]]
set_property PACKAGE_PIN AE6 [get_ports ddr3_dq[6]]
set_property PACKAGE_PIN AC7 [get_ports ddr3_dq[7]]
set_property PACKAGE_PIN AF2 [get_ports ddr3_dq[8]]
set_property PACKAGE_PIN AE1 [get_ports ddr3_dq[9]]
set_property PACKAGE_PIN AD1 [get_ports ddr3_dqs_n[0]]
set_property PACKAGE_PIN AG3 [get_ports ddr3_dqs_n[1]]
set_property PACKAGE_PIN AH1 [get_ports ddr3_dqs_n[2]]
set_property PACKAGE_PIN AJ7 [get_ports ddr3_dqs_n[3]]
set_property PACKAGE_PIN AD2 [get_ports ddr3_dqs_p[0]]
set_property PACKAGE_PIN AG4 [get_ports ddr3_dqs_p[1]]
set_property PACKAGE_PIN AG2 [get_ports ddr3_dqs_p[2]]
set_property PACKAGE_PIN AH7 [get_ports ddr3_dqs_p[3]]
set_property PACKAGE_PIN AK9 [get_ports ddr3_odt[0]]
set_property PACKAGE_PIN AE11 [get_ports ddr3_ras_n]
set_property PACKAGE_PIN AG5 [get_ports ddr3_reset_n]
set_property PACKAGE_PIN AG13 [get_ports ddr3_we_n]


#####################################33
# WISHBONE peripherals
#####################################

# WISHBONE UART: USING JB1 pins: 1: JB1_P=V29, 2: JB1_N=V30
set_property PACKAGE_PIN V29 [get_ports WB_UART_RX]
set_property PACKAGE_PIN V30 [get_ports WB_UART_TX]
set_property IOSTANDARD LVCMOS33 [get_ports WB_UART_RX]
set_property IOSTANDARD LVCMOS33 [get_ports WB_UART_TX]
# fixme: check this
set_property DRIVE 4 [get_ports WB_UART_TX]

##################################
# AXI STUFF
##################################
# AXI VGA
##VGA Connector
# set_property -dict { PACKAGE_PIN A3    IOSTANDARD LVCMOS33 } [get_ports { vga_r_4[0] }]; #IO_L8N_T1_AD14N_35 Sch=vga_r[0]
# set_property -dict { PACKAGE_PIN B4    IOSTANDARD LVCMOS33 } [get_ports { vga_r_4[1] }]; #IO_L7N_T1_AD6N_35 Sch=vga_r[1]
# set_property -dict { PACKAGE_PIN C5    IOSTANDARD LVCMOS33 } [get_ports { vga_r_4[2] }]; #IO_L1N_T0_AD4N_35 Sch=vga_r[2]
# set_property -dict { PACKAGE_PIN A4    IOSTANDARD LVCMOS33 } [get_ports { vga_r_4[3] }]; #IO_L8P_T1_AD14P_35 Sch=vga_r[3]
# set_property -dict { PACKAGE_PIN C6    IOSTANDARD LVCMOS33 } [get_ports { vga_g_4[0] }]; #IO_L1P_T0_AD4P_35 Sch=vga_g[0]
# set_property -dict { PACKAGE_PIN A5    IOSTANDARD LVCMOS33 } [get_ports { vga_g_4[1] }]; #IO_L3N_T0_DQS_AD5N_35 Sch=vga_g[1]
# set_property -dict { PACKAGE_PIN B6    IOSTANDARD LVCMOS33 } [get_ports { vga_g_4[2] }]; #IO_L2N_T0_AD12N_35 Sch=vga_g[2]
# set_property -dict { PACKAGE_PIN A6    IOSTANDARD LVCMOS33 } [get_ports { vga_g_4[3] }]; #IO_L3P_T0_DQS_AD5P_35 Sch=vga_g[3]
# set_property -dict { PACKAGE_PIN B7    IOSTANDARD LVCMOS33 } [get_ports { vga_b_4[0] }]; #IO_L2P_T0_AD12P_35 Sch=vga_b[0]
# set_property -dict { PACKAGE_PIN C7    IOSTANDARD LVCMOS33 } [get_ports { vga_b_4[1] }]; #IO_L4N_T0_35 Sch=vga_b[1]
# set_property -dict { PACKAGE_PIN D7    IOSTANDARD LVCMOS33 } [get_ports { vga_b_4[2] }]; #IO_L6N_T0_VREF_35 Sch=vga_b[2]
# set_property -dict { PACKAGE_PIN D8    IOSTANDARD LVCMOS33 } [get_ports { vga_b_4[3] }]; #IO_L4P_T0_35 Sch=vga_b[3]
# set_property -dict { PACKAGE_PIN B11   IOSTANDARD LVCMOS33 } [get_ports { vga_hsync }]; #IO_L4P_T0_15 Sch=vga_hs
# set_property -dict { PACKAGE_PIN B12   IOSTANDARD LVCMOS33 } [get_ports { vga_vsync }]; #IO_L3N_T0_DQS_AD1N_15 Sch=vga_vs

## VGA Connector
set_property -dict { PACKAGE_PIN AH20  IOSTANDARD LVCMOS33 } [get_ports { vga_b_5[0] }]; #IO_L22N_T3_12 Sch=vga_b[3]
set_property -dict { PACKAGE_PIN AG20  IOSTANDARD LVCMOS33 } [get_ports { vga_b_5[1] }]; #IO_L22P_T3_12 Sch=vga_b[4]
set_property -dict { PACKAGE_PIN AF21  IOSTANDARD LVCMOS33 } [get_ports { vga_b_5[2] }]; #IO_L19N_T3_VREF_12 Sch=vga_b[5]
set_property -dict { PACKAGE_PIN AK20  IOSTANDARD LVCMOS33 } [get_ports { vga_b_5[3] }]; #IO_L24P_T3_12 Sch=vga_b[6]
set_property -dict { PACKAGE_PIN AG22  IOSTANDARD LVCMOS33 } [get_ports { vga_b_5[4] }]; #IO_L20P_T3_12 Sch=vga_b[7]

set_property -dict { PACKAGE_PIN AJ23  IOSTANDARD LVCMOS33 } [get_ports { vga_g_6[0] }]; #IO_L21N_T3_DQS_12 Sch=vga_g[2]
set_property -dict { PACKAGE_PIN AJ22  IOSTANDARD LVCMOS33 } [get_ports { vga_g_6[1] }]; #IO_L21P_T3_DQS_12 Sch=vga_g[3]
set_property -dict { PACKAGE_PIN AH22  IOSTANDARD LVCMOS33 } [get_ports { vga_g_6[2] }]; #IO_L20N_T3_12 Sch=vga_g[4]
set_property -dict { PACKAGE_PIN AK21  IOSTANDARD LVCMOS33 } [get_ports { vga_g_6[3] }]; #IO_L24N_T3_12 Sch=vga_g[5]
set_property -dict { PACKAGE_PIN AJ21  IOSTANDARD LVCMOS33 } [get_ports { vga_g_6[4] }]; #IO_L23N_T3_12 Sch=vga_g[6]
set_property -dict { PACKAGE_PIN AK23  IOSTANDARD LVCMOS33 } [get_ports { vga_g_6[5] }]; #IO_L17P_T2_12 Sch=vga_g[7]

set_property -dict { PACKAGE_PIN AK25  IOSTANDARD LVCMOS33 } [get_ports { vga_r_5[0] }]; #IO_L15N_T2_DQS_12 Sch=vga_r[3]
set_property -dict { PACKAGE_PIN AG25  IOSTANDARD LVCMOS33 } [get_ports { vga_r_5[1] }]; #IO_L18P_T2_12 Sch=vga_r[4]
set_property -dict { PACKAGE_PIN AH25  IOSTANDARD LVCMOS33 } [get_ports { vga_r_5[2] }]; #IO_L18N_T2_12 Sch=vga_r[5]
set_property -dict { PACKAGE_PIN AK24  IOSTANDARD LVCMOS33 } [get_ports { vga_r_5[3] }]; #IO_L17N_T2_12 Sch=vga_r[6]
set_property -dict { PACKAGE_PIN AJ24  IOSTANDARD LVCMOS33 } [get_ports { vga_r_5[4] }]; #IO_L15P_T2_DQS_12 Sch=vga_r[7]

set_property -dict { PACKAGE_PIN AF20  IOSTANDARD LVCMOS33 } [get_ports { vga_hsync }]; #IO_L19P_T3_12 Sch=vga_hs
set_property -dict { PACKAGE_PIN AG23  IOSTANDARD LVCMOS33 } [get_ports { vga_vsync }]; #IO_L13N_T2_MRCC_12 Sch=vga_vs





## AXI USB: JC: JC1=K1=V2P JC2=F6=V1P JC7=E7=V2N JC8=J3=V1N
# AXI USB: JC: JC1=AC26=V2P JC2=AJ27=V1P JC7=AD26=V2N JC8=AG30=V1N
set_property -dict { PACKAGE_PIN AJ27    IOSTANDARD LVCMOS33 } [get_ports { usb0_dp }];
set_property -dict { PACKAGE_PIN AG30    IOSTANDARD LVCMOS33 } [get_ports { usb0_dm }];
set_property -dict { PACKAGE_PIN AC26    IOSTANDARD LVCMOS33 } [get_ports { usb1_dp }];
set_property -dict { PACKAGE_PIN AD26    IOSTANDARD LVCMOS33 } [get_ports { usb1_dm }];
# Not enough but helps
set_property PULLDOWN true [get_ports {usb0_dp usb0_dm usb1_dp usb1_dm}]


## Ethernet
set_property -dict { PACKAGE_PIN AK16  IOSTANDARD LVCMOS18 } [get_ports { rgmii_int_n }]; #IO_L1P_T0_32 Sch=eth_intb
set_property -dict { PACKAGE_PIN AF12  IOSTANDARD LVCMOS15 } [get_ports { rgmii_mdc }]; #IO_L23P_T3_33 Sch=eth_mdc
set_property -dict { PACKAGE_PIN AG12  IOSTANDARD LVCMOS15 } [get_ports { rgmii_mdio }]; #IO_L23N_T3_33 Sch=eth_mdio
set_property -dict { PACKAGE_PIN AH24  IOSTANDARD LVCMOS33 } [get_ports { rgmii_rst_n }]; #IO_L14N_T2_SRCC_12 Sch=eth_phyrst_n
#set_property -dict { PACKAGE_PIN AK15  IOSTANDARD LVCMOS18 } [get_ports { eth_pme_b }]; #IO_L1N_T0_32 Sch=eth_pmeb
set_property -dict { PACKAGE_PIN AG10  IOSTANDARD LVCMOS15 } [get_ports { rgmii_clocks_rx }]; #IO_L13P_T2_MRCC_33 Sch=eth_rx_clk
set_property -dict { PACKAGE_PIN AH11  IOSTANDARD LVCMOS15 } [get_ports { rgmii_rx_ctl }]; #IO_L18P_T2_33 Sch=eth_rx_ctl
set_property -dict { PACKAGE_PIN AJ14  IOSTANDARD LVCMOS15 } [get_ports { rgmii_rx_data[0] }]; #IO_L21N_T3_DQS_33 Sch=eth_rx_d[0]
set_property -dict { PACKAGE_PIN AH14  IOSTANDARD LVCMOS15 } [get_ports { rgmii_rx_data[1] }]; #IO_L21P_T3_DQS_33 Sch=eth_rx_d[1]
set_property -dict { PACKAGE_PIN AK13  IOSTANDARD LVCMOS15 } [get_ports { rgmii_rx_data[2] }]; #IO_L20N_T3_33 Sch=eth_rx_d[2]
set_property -dict { PACKAGE_PIN AJ13  IOSTANDARD LVCMOS15 } [get_ports { rgmii_rx_data[3] }]; #IO_L22P_T3_33 Sch=eth_rx_d[3]
set_property -dict { PACKAGE_PIN AE10  IOSTANDARD LVCMOS15 } [get_ports { rgmii_clocks_tx }]; #IO_L14P_T2_SRCC_33 Sch=eth_tx_clk
set_property -dict { PACKAGE_PIN AJ12  IOSTANDARD LVCMOS15 } [get_ports { rgmii_tx_data[0] }]; #IO_L22N_T3_33 Sch=eth_tx_d[0]
set_property -dict { PACKAGE_PIN AK11  IOSTANDARD LVCMOS15 } [get_ports { rgmii_tx_data[1] }]; #IO_L17P_T2_33 Sch=eth_tx_d[1]
set_property -dict { PACKAGE_PIN AJ11  IOSTANDARD LVCMOS15 } [get_ports { rgmii_tx_data[2] }]; #IO_L18N_T2_33 Sch=eth_tx_d[2]
set_property -dict { PACKAGE_PIN AK10  IOSTANDARD LVCMOS15 } [get_ports { rgmii_tx_data[3] }]; #IO_L17N_T2_33 Sch=eth_tx_d[3]
#set_property -dict { PACKAGE_PIN AK14  IOSTANDARD LVCMOS15 } [get_ports { ETH_TX_EN }]; #IO_L20P_T3_33 Sch=eth_tx_en
set_property -dict { PACKAGE_PIN AK14  IOSTANDARD LVCMOS15 } [get_ports { rgmii_tx_ctl }]; #IO_L20P_T3_33 Sch=eth_tx_en
# INTB needs internal pull-up
set_property PULLUP true [get_ports { rgmii_int_n }]


# Both RGMII and DDR3 are in bank 33 so they cannot be in different IODELAY groups: override anything already set
# LiteEth
set_property IODELAY_GROUP DDR3_IO [get_cells -hier -regexp {^liteEthAXI/u_liteeth/IDELAYE2(_[0-9]+)?$}]
#set_property IODELAY_GROUP DDR3-GROUP [get_cells -hier -regexp {^liteEthAXI/u_liteeth/IDELAYE2(_[0-9]+)?$}]
