module wally_eth_a1_rmii_shim #(
    parameter int REFCLK_HZ = 50_000_000
)(
    input  wire        eth_ref_clk,     // raw from pin
    input  wire [1:0]  eth_rx_data,
    input  wire        eth_crs_dv,
    output wire        eth_tx_en,
    output wire [1:0]  eth_tx_data,
    output wire        eth_mdc,
    inout  wire        eth_mdio,

    output wire [2:0]  GPO              // reuse your LED mapping: GPO[0..2]
);

    // --------------------------------------------------------------------------------------------
    // 1) Make the non-clock-capable pin usable as a clock (we'll BUFG it; XDC will relax routing)
    // --------------------------------------------------------------------------------------------
    wire eth_ref_clk_buf;

    // IBUF is optional; Vivado can infer it. Keeping explicit is fine.
    wire eth_ref_clk_i;
    IBUF u_ibuf_refclk (
        .I(eth_ref_clk),
        .O(eth_ref_clk_i)
    );

    BUFG u_bufg_refclk (
        .I(eth_ref_clk_i),
        .O(eth_ref_clk_buf)
    );

    // --------------------------------------------------------------------------------------------
    // 2) RMII<->MII shim (WangXuan95 rmii_phy_if)
    //    - Hold TX idle for A1: mac_mii_txen=0, mac_mii_txd=0
    //    - Force 100M mode initially (mode_speed=1) so MII clocks = 25 MHz (generated by shim)
    // --------------------------------------------------------------------------------------------
    wire        mii_crs;
    wire        mii_rxrst;
    wire        mii_rxc;
    wire        mii_rxdv;
    wire        mii_rxer;
    wire [3:0]  mii_rxd;

    wire        mii_txrst;
    wire        mii_txc;

    rmii_phy_if u_rmii_phy_if (
        .rstn_async       (1'b1),          // no external reset for A1 (shim self-syncs internally)
        .mode_speed       (1'b1),          // 1=100M, 0=10M

        .mac_mii_crs      (mii_crs),
        .mac_mii_rxrst    (mii_rxrst),
        .mac_mii_rxc      (mii_rxc),
        .mac_mii_rxdv     (mii_rxdv),
        .mac_mii_rxer     (mii_rxer),
        .mac_mii_rxd      (mii_rxd),

        .mac_mii_txrst    (mii_txrst),
        .mac_mii_txc      (mii_txc),
        .mac_mii_txen     (1'b0),
        .mac_mii_txer     (1'b0),
        .mac_mii_txd      (4'h0),

        .phy_rmii_ref_clk (eth_ref_clk_buf),
        .phy_rmii_crsdv   (eth_crs_dv),
        .phy_rmii_rxer    (1'b0),          // RXER not routed on your PMOD mapping (optional in RMII)
        .phy_rmii_rxd     (eth_rx_data),

        .phy_rmii_txen    (eth_tx_en),
        .phy_rmii_txd     (eth_tx_data)
    );

    // --------------------------------------------------------------------------------------------
    // 3) Keep MDIO safe in A1 (Hi-Z), keep MDC low
    // --------------------------------------------------------------------------------------------
    assign eth_mdc = 1'b0;

    // MDIO is open-drain in real use; for A1 we just float it.
    // If you prefer: remove IOBUF and just declare eth_mdio as input with PULLUP in XDC.
    wire mdio_i = 1'b0;
    wire mdio_o;
    wire mdio_t = 1'b1;  // 1 = tri-state (Hi-Z)

    IOBUF u_mdio_iobuf (
        .I(mdio_i),
        .O(mdio_o),
        .T(mdio_t),
        .IO(eth_mdio)
    );

    // --------------------------------------------------------------------------------------------
    // 4) LEDs
    //    - GPO[0]: 1 Hz blink derived from the *RMII 50 MHz ref clock*
    //    - GPO[1]: RX activity stretcher (lights briefly when CRS_DV or RXDV seen)
    //    - GPO[2]: "alive" (just high once running)
    // --------------------------------------------------------------------------------------------

    // Blink: toggle every 0.5s => 1Hz blink (period 1s)
    localparam int BLINK_HALF_PERIOD = REFCLK_HZ/2;
    logic [$clog2(BLINK_HALF_PERIOD)-1:0] blink_cnt = '0;
    logic led_blink = 1'b0;

    always_ff @(posedge eth_ref_clk_buf) begin
        if (blink_cnt == BLINK_HALF_PERIOD-1) begin
            blink_cnt <= '0;
            led_blink <= ~led_blink;
        end else begin
            blink_cnt <= blink_cnt + 1'b1;
        end
    end

    // Activity stretcher ~100ms
    localparam int ACT_MS = 100;
    localparam int ACT_CYCLES = (REFCLK_HZ/1000)*ACT_MS;
    logic [$clog2(ACT_CYCLES+1)-1:0] act_cnt = '0;
    logic led_act = 1'b0;

    wire activity_pulse = eth_crs_dv | mii_rxdv | mii_crs;

    always_ff @(posedge eth_ref_clk_buf) begin
        if (activity_pulse) begin
            act_cnt <= ACT_CYCLES[$clog2(ACT_CYCLES+1)-1:0];
            led_act <= 1'b1;
        end else if (act_cnt != 0) begin
            act_cnt <= act_cnt - 1'b1;
            led_act <= 1'b1;
        end else begin
            led_act <= 1'b0;
        end
    end

    assign GPO[0] = led_blink;
    assign GPO[1] = led_act;
    assign GPO[2] = 1'b1;

endmodule
