# start by reading in all the IP blocks generated by vivado

set partNumber $::env(XILINX_PART)
set boardName $::env(XILINX_BOARD)
set boardSubName [lindex [split ${boardName} :] 1]
set board $::env(board)

#set partNumber xc7a100tcsg324-1
#set boardName digilentinc.com:arty-a7-100:part0:1.1
#set boardSubName arty-a7-100
#set board ArtyA7

#set partNumber xcvu095-ffva2104-2-e
#set boardName xilinx.com:vcu108:part0:1.7
#set boardSubName vcu108
#set board FPU_VCU

set ipName WallyFPGA

create_project $ipName . -force -part $partNumber
if {$boardName!="ArtyA7"} {
    set_property board_part $boardName [current_project]
}

# read package first
add_files  ../src/CopiedFiles_do_not_add_to_repo/cvw.sv
#read_verilog -sv  ../src/wallypipelinedsocwrapper.sv
# then read top level
if {$board=="ArtyA7"} {
    add_files  {../src/fpgaTopArtyA7.sv}
} elseif {$board=="genesys2"} {
    add_files  {../src/fpgaTopGenesys2.sv}
} elseif {$board=="nexysa7"} {
    add_files  {../src/fpgaTopNexysA7.sv}
} elseif {$board=="nexysa7soc" || $board=="nexysa7rv32w64soc"} {
    add_files  {../src/fpgaTopNexysA7SoC.sv}
} elseif {$board=="genesys2soc" || $board=="genesys2rv32soc" || $board=="genesys2rv32w64soc"} {
    add_files  {../src/fpgaTopGenesys2SoC.sv}
} elseif {$board=="genesys2socxlnx"} {
    add_files  {../src/fpgaTopGenesys2SoC.sv}
} else {
    add_files  {../src/fpgaTop.sv}
}

if {$board=="nexysa7soc" || $board=="genesys2soc" || $board=="genesys2rv32soc" || $board=="genesys2rv32w64soc" || $board=="genesys2socxlnx"} {
    add_files  ../../addins/cvwsoc/cvwsoc_axi.sv
}

# read in ip
import_ip IP/sysrst.srcs/sources_1/ip/sysrst/sysrst.xci
if {! ($board == "nexysa7rv32w64soc"  || $board == "genesys2soc" || $board == "genesys2rv32soc" || $board=="genesys2rv32w64soc")} {
import_ip IP/ahbaxibridge.srcs/sources_1/ip/ahbaxibridge/ahbaxibridge.xci
import_ip IP/clkconverter.srcs/sources_1/ip/clkconverter/clkconverter.xci
}

if {$board=="ArtyA7" || $board=="genesys2"} {
    import_ip IP/ddr3.srcs/sources_1/ip/ddr3/ddr3.xci
    import_ip IP/mmcm.srcs/sources_1/ip/mmcm/mmcm.xci
} elseif {$board=="nexysa7" } {
    import_ip IP/ddr2.srcs/sources_1/ip/ddr2/ddr2.xci
    import_ip IP/mmcm.srcs/sources_1/ip/mmcm/mmcm.xci
} elseif {$board=="nexysa7soc" } {
    import_ip IP/mmcm.srcs/sources_1/ip/mmcm/mmcm.xci
    # import_ip IP/ddr2.srcs/sources_1/ip/ddr2/ddr2.xci
} elseif {$board=="nexysa7rv32w64soc" } {
    import_ip IP/mmcm.srcs/sources_1/ip/mmcm/mmcm.xci
    # import_ip IP/ddr2.srcs/sources_1/ip/ddr2/ddr2.xci
} elseif {$board=="genesys2soc" || $board=="genesys2rv32soc" || $board=="genesys2rv32w64soc" } {
    # import_ip IP/ddr3.srcs/sources_1/ip/ddr3/ddr3.xci
    import_ip IP/mmcm.srcs/sources_1/ip/mmcm/mmcm.xci
    # FIXME: remove later
    # import_ip IP/ahbaxibridge.srcs/sources_1/ip/ahbaxibridge/ahbaxibridge.xci
    # import_ip IP/axicdma.srcs/sources_1/ip/axicdma/axicdma.xci
} elseif {$board=="genesys2socxlnx" } {
    import_ip IP/ddr3.srcs/sources_1/ip/ddr3/ddr3.xci
    import_ip IP/mmcm.srcs/sources_1/ip/mmcm/mmcm.xci
    import_ip IP/axicrossbar.srcs/sources_1/ip/axicrossbar/axicrossbar.xci
    import_ip IP/axicdma.srcs/sources_1/ip/axicdma/axicdma.xci
} else {
    import_ip IP/ddr4.srcs/sources_1/ip/ddr4/ddr4.xci
}

# read in all other rtl
add_files [glob -type f  ../src/CopiedFiles_do_not_add_to_repo/*/*.sv ../src/CopiedFiles_do_not_add_to_repo/*/*/*.sv]

set_property include_dirs {../src/CopiedFiles_do_not_add_to_repo/config ../../config/shared} [current_fileset]


# define top level
set_property top fpgaTop [current_fileset]

update_compile_order -fileset sources_1
# This is important as the ddr3/4 IP contains the generate clock constraint which the user constraints depend on.
exec mkdir -p reports/
exec rm -rf reports/*


report_compile_order -constraints > reports/compile_order.rpt

# this is elaboration not synthesis.
#synth_design -rtl -name rtl_1  -flatten_hierarchy none

# apply timing constraint after elaboration
if {$board=="ArtyA7" || $board=="genesys2" || $board=="nexysa7" || $board=="nexysa7soc" || $board=="genesys2soc" } {
    add_files -fileset constrs_1 -norecurse ../constraints/constraints-$board.xdc
    set_property PROCESSING_ORDER NORMAL [get_files  ../constraints/constraints-$board.xdc]
} elseif {$board=="genesys2socxlnx" } {
    add_files -fileset constrs_1 -norecurse ../constraints/constraints-genesys2soc.xdc
    set_property PROCESSING_ORDER NORMAL [get_files  ../constraints/constraints-genesys2soc.xdc]
} elseif {$board=="genesys2rv32soc"  || $board=="genesys2rv32w64soc"} {
    add_files -fileset constrs_1 -norecurse ../constraints/constraints-genesys2soc.xdc
    set_property PROCESSING_ORDER NORMAL [get_files  ../constraints/constraints-genesys2soc.xdc]
} elseif {$board=="nexysa7rv32w64soc"} {
    add_files -fileset constrs_1 -norecurse ../constraints/constraints-nexysa7soc.xdc
    set_property PROCESSING_ORDER NORMAL [get_files  ../constraints/constraints-nexysa7soc.xdc]
} else {
    add_files -fileset constrs_1 -norecurse ../constraints/constraints-$boardSubName.xdc
    set_property PROCESSING_ORDER NORMAL [get_files  ../constraints/constraints-$boardSubName.xdc]
}

# only tested on the Genesys 2
if {$board=="nexysa7soc" || $board=="nexysa7rv32w64soc" || $board=="genesys2soc" || $board=="genesys2rv32soc" || $board=="genesys2rv32w64soc"} {

    add_files  ../src/CopiedFiles_do_not_add_to_repo/cvwsoc/cvwsoc_pkg.sv

    set uberddr3_supported [expr {[info exists ::env(UBERDDR3_SUPPORTED)] ? $::env(UBERDDR3_SUPPORTED) : "0"}]
    set litedram_supported  [expr {[info exists ::env(LITEDRAM_SUPPORTED)]  ? $::env(LITEDRAM_SUPPORTED)  : "0"}]

    puts "DEBUG uberddr3_supported=($uberddr3_supported)"
    puts "DEBUG litedram_supported=($litedram_supported)"

    if {$litedram_supported=="1"} {
        if { $board=="genesys2rv32soc"  || $board=="genesys2rv32w64soc"} {
            add_files -fileset constrs_1 -norecurse ../constraints/constraints-genesys2soc-litedram.xdc
            set_property PROCESSING_ORDER NORMAL [get_files  ../constraints/constraints-genesys2soc-litedram.xdc]
        } elseif { $board=="nexysa7rv32w64soc" } {
            add_files -fileset constrs_1 -norecurse ../constraints/constraints-nexysa7soc-litedram.xdc
            set_property PROCESSING_ORDER NORMAL [get_files  ../constraints/constraints-nexysa7soc-litedram.xdc]
        } else {
            add_files -fileset constrs_1 -norecurse ../constraints/constraints-$board-litedram.xdc
            set_property PROCESSING_ORDER NORMAL [get_files  ../constraints/constraints-$board-litedram.xdc]
        }
    } elseif {$uberddr3_supported=="1"} {
        if { $board=="genesys2rv32soc"  || $board=="genesys2rv32w64soc"} {
            add_files -fileset constrs_1 -norecurse ../constraints/constraints-genesys2soc-uberddr3.xdc
            set_property PROCESSING_ORDER NORMAL [get_files  ../constraints/constraints-genesys2soc-uberddr3.xdc]
        } else {
            add_files -fileset constrs_1 -norecurse ../constraints/constraints-$board-uberddr3.xdc
            set_property PROCESSING_ORDER NORMAL [get_files  ../constraints/constraints-$board-uberddr3.xdc]
        }
    } else {
        if { $board=="genesys2rv32soc"  || $board=="genesys2rv32w64soc"} {
            add_files -fileset constrs_1 -norecurse ../constraints/constraints-genesys2soc-mig.xdc
            set_property PROCESSING_ORDER NORMAL [get_files  ../constraints/constraints-genesys2soc-mig.xdc]
            puts "DEBUG Using Xilinx MIG"
        } elseif {$board=="nexysa7rv32w64soc"} {
            add_files -fileset constrs_1 -norecurse ../constraints/constraints-nexysa7soc-mig.xdc
            set_property PROCESSING_ORDER NORMAL [get_files  ../constraints/constraints-nexysa7soc-mig.xdc]
            puts "DEBUG Using Xilinx MIG"
        } else {
            add_files -fileset constrs_1 -norecurse ../constraints/constraints-$board-mig.xdc
            set_property PROCESSING_ORDER NORMAL [get_files  ../constraints/constraints-$board-mig.xdc]
            puts "DEBUG Using Xilinx MIG"
        }
    }
}

if {$board=="nexysa7soc" || $board=="nexysa7rv32w64soc" || $board=="genesys2soc"  || $board=="genesys2rv32soc" || $board=="genesys2rv32w64soc" || $board=="genesys2socxlnx"} {

    set_property include_dirs {../src/CopiedFiles_do_not_add_to_repo/config ../../config/shared \
        ../src/CopiedFiles_do_not_add_to_repo/cvwsoc \
        ../src/CopiedFiles_do_not_add_to_repo/oc_uart_16550 \
        ../src/CopiedFiles_do_not_add_to_repo/sdhci/hw/include \
        ../src/CopiedFiles_do_not_add_to_repo/pulp/register_interface/include \
        ../src/CopiedFiles_do_not_add_to_repo/pulp/axi/include \
        ../../addins/pulp/axi_stream/include \
        ../src/CopiedFiles_do_not_add_to_repo/pulp/idma/src/include \
        ../src/CopiedFiles_do_not_add_to_repo/pulp/common_cells/include} [current_fileset]

    # cvwsoc stuff
    add_files [glob -type f  ../src/CopiedFiles_do_not_add_to_repo/cvwsoc/*/*.v ../src/CopiedFiles_do_not_add_to_repo/cvwsoc/*/*.sv]
    # Pulp files
    add_files [glob -type f  ../src/CopiedFiles_do_not_add_to_repo/pulp/*/src/*.sv]
    # FIXME: what to do with patches in this 'vendor' subfolder?
    add_files [glob -type f  ../src/CopiedFiles_do_not_add_to_repo/pulp/register_interface/vendor/*/src/*.sv]
    # verilog-axi stuff
    add_files [glob -type f  ../src/CopiedFiles_do_not_add_to_repo/verilog-axi/rtl/*.v]
    # AXI-Stream to I2S audio path
    add_files [glob -type f  ../src/CopiedFiles_do_not_add_to_repo/verilog-axis/rtl/*.v]
    add_files [glob -type f  ../src/CopiedFiles_do_not_add_to_repo/digilent-i2s2/*.v]
    # oc uart stuff
    add_files [glob -type f  ../src/CopiedFiles_do_not_add_to_repo/oc_uart_16550/*.v]
    # ahb3lite_wb_bridge stuff
    add_files [glob -type f  ../src/CopiedFiles_do_not_add_to_repo/ahb3lite_wb_bridge/*.v]
    # wb2axip stuff: only specific files for now
    add_files [glob -type f  ../src/CopiedFiles_do_not_add_to_repo/wb2axip/rtl/axlite2wbsp.v \
        ../src/CopiedFiles_do_not_add_to_repo/wb2axip/rtl/axilwr2wbsp.v \
        ../src/CopiedFiles_do_not_add_to_repo/wb2axip/rtl/axilrd2wbsp.v  \
        ../src/CopiedFiles_do_not_add_to_repo/wb2axip/rtl/wbarbiter.v  \
        ]
    # uberddr3 stuff
    add_files [glob -type f  ../src/CopiedFiles_do_not_add_to_repo/uberddr3/rtl/*.v \
                             ../src/CopiedFiles_do_not_add_to_repo/uberddr3/rtl/axi/*.v \
        ]
    # SDHCI stuff
    add_files [glob -type f  ../src/CopiedFiles_do_not_add_to_repo/pulp/tech_cells/src/rtl/*.sv]
    add_files [glob -type f  ../src/CopiedFiles_do_not_add_to_repo/pulp/tech_cells/src/fpga/*.sv]
    add_files [glob -type f  ../src/CopiedFiles_do_not_add_to_repo/sdhci/hw/*.sv \
                             ../src/CopiedFiles_do_not_add_to_repo/sdhci/hw/*/*.sv \
        ]

    # iDMA stuff
    add_files [glob -type f  ../src/CopiedFiles_do_not_add_to_repo/pulp/idma/src/idma_pkg.sv]
    add_files [glob -type f  ../src/CopiedFiles_do_not_add_to_repo/pulp/idma/src/backend/*.sv]
    add_files [glob -type f  ../src/CopiedFiles_do_not_add_to_repo/pulp/idma/src/frontend/idma_transfer_id_gen.sv]
    add_files [glob -type f  ../src/CopiedFiles_do_not_add_to_repo/pulp/idma/src/frontend/desc64/idma_desc64_ar_gen.sv]
    add_files [glob -type f  ../src/CopiedFiles_do_not_add_to_repo/pulp/idma/src/frontend/desc64/idma_desc64_ar_gen_prefetch.sv]
    add_files [glob -type f  ../src/CopiedFiles_do_not_add_to_repo/pulp/idma/src/frontend/desc64/idma_desc64_reader.sv]
    add_files [glob -type f  ../src/CopiedFiles_do_not_add_to_repo/pulp/idma/src/frontend/desc64/idma_desc64_reader_gater.sv]
    add_files [glob -type f  ../src/CopiedFiles_do_not_add_to_repo/pulp/idma/src/frontend/desc64/idma_desc64_reshaper.sv]
    add_files [glob -type f  ../src/CopiedFiles_do_not_add_to_repo/pulp/idma/src/frontend/desc64/idma_desc64_reg_wrapper.sv]
    add_files [glob -type f  ../src/CopiedFiles_do_not_add_to_repo/pulp/idma/src/frontend/desc64/idma_desc64_top.sv]
    add_files [glob -type f  ../src/CopiedFiles_do_not_add_to_repo/pulp/idma/src/frontend/desc64/idma_desc64_axi_axis*.sv]
    # iDMA: generated RTL
    add_files [glob -type f  ../src/CopiedFiles_do_not_add_to_repo/pulp/idma/target/rtl/idma_transport_layer_rw_axi_rw_axis.sv]
    add_files [glob -type f  ../src/CopiedFiles_do_not_add_to_repo/pulp/idma/target/rtl/idma_legalizer_rw_axi_rw_axis.sv]
    add_files [glob -type f  ../src/CopiedFiles_do_not_add_to_repo/pulp/idma/target/rtl/idma_backend_rw_axi_rw_axis.sv]
    add_files [glob -type f  ../src/CopiedFiles_do_not_add_to_repo/pulp/idma/target/rtl/idma_desc64_reg_pkg.sv]
    add_files [glob -type f  ../src/CopiedFiles_do_not_add_to_repo/pulp/idma/target/rtl/idma_desc64_reg_top.sv]
    add_files [glob -type f  ../src/CopiedFiles_do_not_add_to_repo/pulp/idma/target/rtl/idma_reg64_1d_reg_pkg.sv]
    add_files [glob -type f  ../src/CopiedFiles_do_not_add_to_repo/pulp/idma/target/rtl/idma_reg64_1d_reg_top.sv]
    add_files [glob -type f  ../src/CopiedFiles_do_not_add_to_repo/pulp/idma/target/rtl/idma_reg64_1d_top.sv]

    report_compile_order -constraints > reports/compile_order.rpt
}

set_param messaging.defaultLimit 100000
if {$board=="nexysa7soc" || $board=="nexysa7rv32w64soc" || $board=="genesys2soc"  || $board=="genesys2rv32soc" || $board=="genesys2rv32w64soc" || $board=="genesys2socxlnx"} {
    set_param general.maxThreads 16

    puts "###########################################################################"
    report_property -all [get_runs synth_1]
    puts "###########################################################################"
    report_compile_order -fileset sources_1 -used_in synthesis -sources
    puts "###########################################################################"
}


launch_runs synth_1 -jobs 16

wait_on_run synth_1
open_run synth_1

report_clocks -file reports/clocks.rpt

check_timing -verbose                                                   -file reports/check_timing.rpt
report_timing -max_paths 10 -nworst 10 -delay_type max -sort_by slack   -file reports/timing_WORST_10.rpt
report_timing -nworst 1 -delay_type max -sort_by group                  -file reports/timing.rpt
report_utilization -hierarchical                                        -file reports/utilization.rpt
report_cdc                                                              -file reports/cdc.rpt
report_clock_interaction                                                -file reports/clock_interaction.rpt

write_verilog -force -mode funcsim sim/syn-funcsim.v

if {$board=="ArtyA7"} {
    #source ../constraints/small-debug.xdc
    #source ../constraints/small-debug-rvvi.xdc
    source ../constraints/small-debug-wfi.xdc
} elseif {$board=="genesys2"} {
    source ../constraints/small-debug.xdc
} elseif {$board=="nexysa7"} {
    source ../constraints/small-debug.xdc
} elseif {$board=="nexysa7soc"} {
    #source ../constraints/small-debug.xdc
    #source ../constraints/debug-nexysa7.xdc
    #source ../constraints/debug-wishbone.xdc
    #source ../constraints/debug-usb.xdc
    #source ../constraints/big-debug-spi.xdc
    #source ../constraints/debug-spi.xdc
    # NO ILA
    # source ../constraints/debug-boot-tiny.xdc
} elseif {$board=="nexysa7rv32w64soc"} {
    source ../constraints/debug-boot-tiny.xdc
} elseif {$board=="genesys2rv32w64soc" || $board=="genesys2soc" || $board=="genesys2rv32soc" || $board=="genesys2rv32w64soc" ||$board=="genesys2socxlnx" } {
    source ../constraints/debug-boot.xdc
} else {
    #source ../constraints/vcu-small-debug.xdc
    #source ../constraints/small-debug.xdc
    #source ../constraints/small-debug.xdc
    source ../constraints/big-debug-spi.xdc
}

# WIP: bridge debugging
#if {$board=="nexysa7soc" || $board=="genesys2soc"  || $board=="genesys2rv32soc" || $board=="genesys2rv32w64soc" || $board=="genesys2socdebug"} {
#        source ../constraints/debug-ahb-axi-bridge.xdc
#}

# by default no space for probes in Nexys A7
if {$board=="genesys2soc" || $board=="genesys2rv32soc" || $board=="genesys2rv32w64soc"} {
    if {$litedram_supported=="1"} {
        source ../constraints/debug-boot-litedram.xdc
    } elseif {$uberddr3_supported=="1"} {
        source ../constraints/debug-boot-uberddr3.xdc
    } else {
        source ../constraints/debug-boot-mig.xdc
    }
}


# set for RuntimeOptimized implementation
# set_property "steps.place_design.args.directive" "RuntimeOptimized" [get_runs impl_1]
# set_property "steps.route_design.args.directive" "RuntimeOptimized" [get_runs impl_1]

###########################################
# options for faster builds (beware of later 'set_property strategy')
###########################################
if {$board=="nexysa7soc"} {
    # set_property "steps.place_design.args.directive" "Quick" [get_runs impl_1]
    # set_property "steps.route_design.args.directive" "Quick" [get_runs impl_1]
    # set_property STEPS.PLACE_DESIGN.ARGS.DIRECTIVE Quick            [get_runs impl_1]  ;
    # set_property STEPS.ROUTE_DESIGN.ARGS.DIRECTIVE Quick            [get_runs impl_1]  ;
    # set_property STEPS.OPT_DESIGN.ARGS.DIRECTIVE   RuntimeOptimized [get_runs impl_1]  ;

    # set_property STEPS.PHYS_OPT_DESIGN.IS_ENABLED false [get_runs impl_1]
    # set_property STEPS.POST_ROUTE_PHYS_OPT_DESIGN.IS_ENABLED false [get_runs impl_1]
}


if {$board=="nexysa7soc" || $board=="nexysa7rv32w64soc" || $board=="genesys2soc" || $board=="genesys2rv32soc" || $board=="genesys2rv32w64soc" || $board=="genesys2socxlnx"} {
    #set_property STEPS.ROUTE_DESIGN.ARGS.ULTRATHREADS true [get_runs impl_1] #doesn't exist
    #set_property "STEPS.ROUTE_DESIGN.ARGS.MORE OPTIONS" "-ultrathreads -no_psir" [get_runs impl_1]
    # set_property -name "STEPS.ROUTE_DESIGN.ARGS.MORE OPTIONS" \
    #             -value "-ultrathreads -no_psir" \
    #             -objects [get_runs impl_1]
    #set_property STEPS.ROUTE_DESIGN.ARGS.NO_PSIR      true [get_runs impl_1]
    # Quick already implies non-timing-driven, but if not using Quick:
    # set_property STEPS.ROUTE_DESIGN.ARGS.NO_TIMING_DRIVEN true [get_runs impl_1]

    set_param general.maxThreads 8

    # ---- FAST/INCR knobs (put before launch_runs impl_1) ----
    # set prev_routed_dcp [file normalize "./WallyFPGA.runs/impl_1/fpgaTop_routed.dcp"]
    # if {[file exists $prev_routed_dcp]} {
    #     set_property INCREMENTAL_CHECKPOINT $prev_routed_dcp [get_runs impl_1]
    #     set_property AUTO_INCREMENTAL_CHECKPOINT 0 [get_runs impl_1] ;# keep explicit reference
    # }
    # Or use auto mode instead:
    # set_property AUTO_INCREMENTAL_CHECKPOINT 1 [get_runs impl_1]
}

# Further optimization tuning
if {$board=="nexysa7soc" || $board=="nexysa7rv32w64soc" || $board=="genesys2soc" || $board=="genesys2rv32soc" || $board=="genesys2rv32w64soc"} {

    # WARNING: set_property strategy resets some properties' values (CHECKME!!)

    # extra post-route physical optimization step that can help with critical paths (but takes time)
    # WARNING: this option crashed Vivado at some point (maybe it's the combination with other options)
    #set_property strategy Performance_ExplorePostRoutePhysOpt [get_runs impl_1]

    # Strategy targets high fanout (AXI VGA) => Better than Performance_ExplorePostRoutePhysOpt
    # REMOVED FOR NOW
    # set_property strategy Performance_WLBlockPlacementFanoutOpt [get_runs impl_1]
}

if {$board=="nexysa7soc" || $board=="nexysa7rv32w64soc" || $board=="genesys2soc" || $board=="genesys2rv32soc" || $board=="genesys2rv32w64soc" || $board=="genesys2socxlnx"} {
    if {$board=="genesys2socxlnx" || $board=="genesys2rv32soc" || $board=="genesys2rv32w64soc" } {
        set hook [file normalize ../constraints/constraints-genesys2soc-timing.tcl]
    } elseif {$board=="nexysa7soc" || $board=="nexysa7rv32w64soc"} {
        set hook [file normalize ../constraints/constraints-cvwsoc-timing.tcl]
    } else {
        set hook [file normalize ../constraints/constraints-$board-timing.tcl]
    }
    set_property STEPS.INIT_DESIGN.TCL.POST $hook [get_runs impl_1]

    # CHECK!! MIGHT NOT BE NEEDED LATER (supposedly takes long!!)
    # phys_opt_design is an optional QoR pass
    # is this causing Vivado crashes 2024.2 crashes??
    #set_property STEPS.POST_ROUTE_PHYS_OPT_DESIGN.IS_ENABLED true [get_runs impl_1]

    set_property STEPS.INIT_DESIGN.TCL.POST $hook [get_runs impl_1]

    # WARNING: maybe this option also made it crash?? same option as above?
    #set_property STEPS.POST_ROUTE_PHYS_OPT_DESIGN.ARGS.DIRECTIVE Explore [get_runs impl_1]

    # This power optimization step was taking REALLY long in some builds
    set_property STEPS.OPT_DESIGN.ARGS.DIRECTIVE NoBramPowerOpt [get_runs impl_1]

    # needed to be able to set STEPS.INIT_DESIGN.TCL.POST?
    reset_runs impl_1
}

launch_runs impl_1 -jobs 12
if {$board=="nexysa7soc" || $board=="nexysa7rv32w64soc" || $board=="genesys2soc" || $board=="genesys2rv32soc" || $board=="genesys2rv32w64soc" || $board=="genesys2socxlnx" } {
    puts "###########################################################################"
    report_property -all [get_runs impl_1]
    puts "###########################################################################"
}
wait_on_run impl_1
launch_runs impl_1 -to_step write_bitstream -jobs 16
wait_on_run impl_1
open_run impl_1

# output Verilog netlist + SDC for timing simulation
exec mkdir -p sim/
exec rm -rf sim/*

write_verilog -force -mode funcsim sim/imp-funcsim.v
write_verilog -force -mode timesim sim/imp-timesim.v
write_sdf     -force sim/imp-timesim.sdf

# reports
check_timing                                                              -file reports/imp_check_timing.rpt
report_timing -max_paths 10 -nworst 10 -delay_type max -sort_by slack     -file reports/imp_timing_WORST_10.rpt
report_timing -nworst 1 -delay_type max -sort_by group                    -file reports/imp_timing.rpt
report_utilization -hierarchical                                          -file reports/imp_utilization.rpt

if {$board=="nexysa7soc" || $board=="nexysa7rv32w64soc" || $board=="genesys2soc" || $board=="genesys2rv32soc" || $board=="genesys2rv32w64soc"} {
    write_project_tcl -force $ipName.tcl
}
