# Minimal Genesys 2 constraints for the OpenXC7 experiment.
# This is a reduced XDC subset: pins and basic I/O standards only.

set_property PACKAGE_PIN AD12 [get_ports default_200mhz_clk_p]
set_property PACKAGE_PIN AD11 [get_ports default_200mhz_clk_n]
set_property IOSTANDARD LVDS [get_ports default_200mhz_clk_p]
set_property IOSTANDARD LVDS [get_ports default_200mhz_clk_n]

# v2: Genesys2 slide switches SW0..SW3, not push buttons.
# set_property PACKAGE_PIN E18 [get_ports {GPI[0]}]
# set_property PACKAGE_PIN M19 [get_ports {GPI[1]}]
# set_property PACKAGE_PIN M20 [get_ports {GPI[2]}]
# set_property PACKAGE_PIN C19 [get_ports {GPI[3]}]
set_property PACKAGE_PIN G19 [get_ports {GPI[0]}]
set_property PACKAGE_PIN G25 [get_ports {GPI[1]}]
set_property PACKAGE_PIN H24 [get_ports {GPI[2]}]
set_property PACKAGE_PIN K19 [get_ports {GPI[3]}]
set_property IOSTANDARD LVCMOS12 [get_ports {GPI[0]}]
set_property IOSTANDARD LVCMOS12 [get_ports {GPI[1]}]
set_property IOSTANDARD LVCMOS12 [get_ports {GPI[2]}]
set_property IOSTANDARD LVCMOS12 [get_ports {GPI[3]}]

set_property PACKAGE_PIN T28 [get_ports {GPO[0]}]
set_property PACKAGE_PIN V19 [get_ports {GPO[1]}]
set_property PACKAGE_PIN U30 [get_ports {GPO[2]}]
set_property PACKAGE_PIN U29 [get_ports {GPO[3]}]
set_property PACKAGE_PIN V20 [get_ports {GPO[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPO[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPO[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPO[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPO[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPO[4]}]

set_property PACKAGE_PIN W23 [get_ports LED7]
set_property IOSTANDARD LVCMOS33 [get_ports LED7]
set_property PACKAGE_PIN W24 [get_ports LED6]
set_property IOSTANDARD LVCMOS33 [get_ports LED6]
set_property PACKAGE_PIN V26 [get_ports LED5]
set_property IOSTANDARD LVCMOS33 [get_ports LED5]

set_property PACKAGE_PIN Y20 [get_ports UARTSin]
set_property PACKAGE_PIN Y23 [get_ports UARTSout]
set_property IOSTANDARD LVCMOS33 [get_ports UARTSin]
set_property IOSTANDARD LVCMOS33 [get_ports UARTSout]

# Manta debug UART on Genesys 2 PMOD JB.
set_property PACKAGE_PIN V25 [get_ports debugIn]
set_property PACKAGE_PIN W26 [get_ports debugOut]
set_property IOSTANDARD LVCMOS33 [get_ports debugIn]
set_property IOSTANDARD LVCMOS33 [get_ports debugOut]

# SPI-mode SD card socket, matching fpga/constraints/constraints-genesys2soc.xdc.
set_property PACKAGE_PIN V27 [get_ports SDCCS]
set_property IOSTANDARD LVCMOS33 [get_ports SDCCS]
set_property PULLTYPE PULLUP [get_ports SDCCS]
set_property PACKAGE_PIN V24 [get_ports SDCIn]
set_property IOSTANDARD LVCMOS33 [get_ports SDCIn]
set_property PULLTYPE PULLUP [get_ports SDCIn]
set_property PACKAGE_PIN W22 [get_ports SDCCLK]
set_property IOSTANDARD LVCMOS33 [get_ports SDCCLK]
set_property PULLTYPE PULLUP [get_ports SDCCLK]
set_property PACKAGE_PIN Y30 [get_ports SDCCmd]
set_property IOSTANDARD LVCMOS33 [get_ports SDCCmd]
set_property PULLTYPE PULLUP [get_ports SDCCmd]
set_property PACKAGE_PIN V22 [get_ports SDCCD]
set_property IOSTANDARD LVCMOS33 [get_ports SDCCD]
set_property PULLTYPE PULLUP [get_ports SDCCD]
set_property PACKAGE_PIN W21 [get_ports SDCWP]
set_property IOSTANDARD LVCMOS33 [get_ports SDCWP]
set_property PULLTYPE PULLUP [get_ports SDCWP]

set_property PACKAGE_PIN B19 [get_ports south_reset]
set_property PACKAGE_PIN R19 [get_ports resetn]
set_property IOSTANDARD LVCMOS12 [get_ports south_reset]
set_property IOSTANDARD LVCMOS33 [get_ports resetn]

set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[0]}]
set_property SLEW FAST [get_ports {ddr3_dq[0]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[1]}]
set_property SLEW FAST [get_ports {ddr3_dq[1]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[2]}]
set_property SLEW FAST [get_ports {ddr3_dq[2]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[3]}]
set_property SLEW FAST [get_ports {ddr3_dq[3]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[4]}]
set_property SLEW FAST [get_ports {ddr3_dq[4]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[5]}]
set_property SLEW FAST [get_ports {ddr3_dq[5]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[6]}]
set_property SLEW FAST [get_ports {ddr3_dq[6]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[7]}]
set_property SLEW FAST [get_ports {ddr3_dq[7]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[8]}]
set_property SLEW FAST [get_ports {ddr3_dq[8]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[9]}]
set_property SLEW FAST [get_ports {ddr3_dq[9]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[10]}]
set_property SLEW FAST [get_ports {ddr3_dq[10]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[11]}]
set_property SLEW FAST [get_ports {ddr3_dq[11]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[12]}]
set_property SLEW FAST [get_ports {ddr3_dq[12]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[13]}]
set_property SLEW FAST [get_ports {ddr3_dq[13]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[14]}]
set_property SLEW FAST [get_ports {ddr3_dq[14]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[15]}]
set_property SLEW FAST [get_ports {ddr3_dq[15]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[16]}]
set_property SLEW FAST [get_ports {ddr3_dq[16]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[17]}]
set_property SLEW FAST [get_ports {ddr3_dq[17]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[18]}]
set_property SLEW FAST [get_ports {ddr3_dq[18]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[19]}]
set_property SLEW FAST [get_ports {ddr3_dq[19]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[20]}]
set_property SLEW FAST [get_ports {ddr3_dq[20]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[21]}]
set_property SLEW FAST [get_ports {ddr3_dq[21]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[22]}]
set_property SLEW FAST [get_ports {ddr3_dq[22]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[23]}]
set_property SLEW FAST [get_ports {ddr3_dq[23]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[24]}]
set_property SLEW FAST [get_ports {ddr3_dq[24]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[25]}]
set_property SLEW FAST [get_ports {ddr3_dq[25]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[26]}]
set_property SLEW FAST [get_ports {ddr3_dq[26]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[27]}]
set_property SLEW FAST [get_ports {ddr3_dq[27]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[28]}]
set_property SLEW FAST [get_ports {ddr3_dq[28]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[29]}]
set_property SLEW FAST [get_ports {ddr3_dq[29]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[30]}]
set_property SLEW FAST [get_ports {ddr3_dq[30]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[31]}]
set_property SLEW FAST [get_ports {ddr3_dq[31]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dm[0]}]
set_property SLEW FAST [get_ports {ddr3_dm[0]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dm[1]}]
set_property SLEW FAST [get_ports {ddr3_dm[1]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dm[2]}]
set_property SLEW FAST [get_ports {ddr3_dm[2]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dm[3]}]
set_property SLEW FAST [get_ports {ddr3_dm[3]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {ddr3_dqs_p[0]}]
set_property SLEW FAST [get_ports {ddr3_dqs_p[0]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {ddr3_dqs_n[0]}]
set_property SLEW FAST [get_ports {ddr3_dqs_n[0]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {ddr3_dqs_p[1]}]
set_property SLEW FAST [get_ports {ddr3_dqs_p[1]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {ddr3_dqs_n[1]}]
set_property SLEW FAST [get_ports {ddr3_dqs_n[1]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {ddr3_dqs_p[2]}]
set_property SLEW FAST [get_ports {ddr3_dqs_p[2]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {ddr3_dqs_n[2]}]
set_property SLEW FAST [get_ports {ddr3_dqs_n[2]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {ddr3_dqs_p[3]}]
set_property SLEW FAST [get_ports {ddr3_dqs_p[3]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {ddr3_dqs_n[3]}]
set_property SLEW FAST [get_ports {ddr3_dqs_n[3]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[0]}]
set_property SLEW FAST [get_ports {ddr3_addr[0]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[1]}]
set_property SLEW FAST [get_ports {ddr3_addr[1]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[2]}]
set_property SLEW FAST [get_ports {ddr3_addr[2]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[3]}]
set_property SLEW FAST [get_ports {ddr3_addr[3]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[4]}]
set_property SLEW FAST [get_ports {ddr3_addr[4]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[5]}]
set_property SLEW FAST [get_ports {ddr3_addr[5]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[6]}]
set_property SLEW FAST [get_ports {ddr3_addr[6]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[7]}]
set_property SLEW FAST [get_ports {ddr3_addr[7]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[8]}]
set_property SLEW FAST [get_ports {ddr3_addr[8]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[9]}]
set_property SLEW FAST [get_ports {ddr3_addr[9]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[10]}]
set_property SLEW FAST [get_ports {ddr3_addr[10]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[11]}]
set_property SLEW FAST [get_ports {ddr3_addr[11]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[12]}]
set_property SLEW FAST [get_ports {ddr3_addr[12]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[13]}]
set_property SLEW FAST [get_ports {ddr3_addr[13]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[14]}]
set_property SLEW FAST [get_ports {ddr3_addr[14]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_ba[0]}]
set_property SLEW FAST [get_ports {ddr3_ba[0]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_ba[1]}]
set_property SLEW FAST [get_ports {ddr3_ba[1]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_ba[2]}]
set_property SLEW FAST [get_ports {ddr3_ba[2]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {ddr3_ck_p[0]}]
set_property SLEW FAST [get_ports {ddr3_ck_p[0]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {ddr3_ck_n[0]}]
set_property SLEW FAST [get_ports {ddr3_ck_n[0]}]
set_property IOSTANDARD SSTL15 [get_ports ddr3_ras_n]
set_property SLEW FAST [get_ports ddr3_ras_n]
set_property IOSTANDARD SSTL15 [get_ports ddr3_cas_n]
set_property SLEW FAST [get_ports ddr3_cas_n]
set_property IOSTANDARD SSTL15 [get_ports ddr3_we_n]
set_property SLEW FAST [get_ports ddr3_we_n]
set_property IOSTANDARD LVCMOS15 [get_ports ddr3_reset_n]
set_property SLEW FAST [get_ports ddr3_reset_n]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_cke[0]}]
set_property SLEW FAST [get_ports {ddr3_cke[0]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_odt[0]}]
set_property SLEW FAST [get_ports {ddr3_odt[0]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_cs_n[0]}]
set_property SLEW FAST [get_ports {ddr3_cs_n[0]}]
# nextpnr-xilinx reports these width-1 vector ports as scalar PAD names
# after IO buffer insertion, so keep scalar aliases for the same pins.
set_property IOSTANDARD DIFF_SSTL15 [get_ports ddr3_ck_p]
set_property SLEW FAST [get_ports ddr3_ck_p]
set_property IOSTANDARD DIFF_SSTL15 [get_ports ddr3_ck_n]
set_property SLEW FAST [get_ports ddr3_ck_n]
set_property IOSTANDARD SSTL15 [get_ports ddr3_cke]
set_property SLEW FAST [get_ports ddr3_cke]
set_property IOSTANDARD SSTL15 [get_ports ddr3_odt]
set_property SLEW FAST [get_ports ddr3_odt]
set_property IOSTANDARD SSTL15 [get_ports ddr3_cs_n]
set_property SLEW FAST [get_ports ddr3_cs_n]

set_property PACKAGE_PIN AC12 [get_ports {ddr3_addr[0]}]
set_property PACKAGE_PIN AE8 [get_ports {ddr3_addr[1]}]
set_property PACKAGE_PIN AD8 [get_ports {ddr3_addr[2]}]
set_property PACKAGE_PIN AC10 [get_ports {ddr3_addr[3]}]
set_property PACKAGE_PIN AD9 [get_ports {ddr3_addr[4]}]
set_property PACKAGE_PIN AA13 [get_ports {ddr3_addr[5]}]
set_property PACKAGE_PIN AA10 [get_ports {ddr3_addr[6]}]
set_property PACKAGE_PIN AA11 [get_ports {ddr3_addr[7]}]
set_property PACKAGE_PIN Y10 [get_ports {ddr3_addr[8]}]
set_property PACKAGE_PIN Y11 [get_ports {ddr3_addr[9]}]
set_property PACKAGE_PIN AB8 [get_ports {ddr3_addr[10]}]
set_property PACKAGE_PIN AA8 [get_ports {ddr3_addr[11]}]
set_property PACKAGE_PIN AB12 [get_ports {ddr3_addr[12]}]
set_property PACKAGE_PIN AA12 [get_ports {ddr3_addr[13]}]
set_property PACKAGE_PIN AH9 [get_ports {ddr3_addr[14]}]
set_property PACKAGE_PIN AE9 [get_ports {ddr3_ba[0]}]
set_property PACKAGE_PIN AB10 [get_ports {ddr3_ba[1]}]
set_property PACKAGE_PIN AC11 [get_ports {ddr3_ba[2]}]
set_property PACKAGE_PIN AF11 [get_ports ddr3_cas_n]
set_property PACKAGE_PIN AC9 [get_ports {ddr3_ck_n[0]}]
set_property PACKAGE_PIN AB9 [get_ports {ddr3_ck_p[0]}]
set_property PACKAGE_PIN AJ9 [get_ports {ddr3_cke[0]}]
set_property PACKAGE_PIN AH12 [get_ports {ddr3_cs_n[0]}]
set_property PACKAGE_PIN AC9 [get_ports ddr3_ck_n]
set_property PACKAGE_PIN AB9 [get_ports ddr3_ck_p]
set_property PACKAGE_PIN AJ9 [get_ports ddr3_cke]
set_property PACKAGE_PIN AH12 [get_ports ddr3_cs_n]
set_property PACKAGE_PIN AD4 [get_ports {ddr3_dm[0]}]
set_property PACKAGE_PIN AF3 [get_ports {ddr3_dm[1]}]
set_property PACKAGE_PIN AH4 [get_ports {ddr3_dm[2]}]
set_property PACKAGE_PIN AF8 [get_ports {ddr3_dm[3]}]
set_property PACKAGE_PIN AD3 [get_ports {ddr3_dq[0]}]
set_property PACKAGE_PIN AC2 [get_ports {ddr3_dq[1]}]
set_property PACKAGE_PIN AC1 [get_ports {ddr3_dq[2]}]
set_property PACKAGE_PIN AC5 [get_ports {ddr3_dq[3]}]
set_property PACKAGE_PIN AC4 [get_ports {ddr3_dq[4]}]
set_property PACKAGE_PIN AD6 [get_ports {ddr3_dq[5]}]
set_property PACKAGE_PIN AE6 [get_ports {ddr3_dq[6]}]
set_property PACKAGE_PIN AC7 [get_ports {ddr3_dq[7]}]
set_property PACKAGE_PIN AF2 [get_ports {ddr3_dq[8]}]
set_property PACKAGE_PIN AE1 [get_ports {ddr3_dq[9]}]
set_property PACKAGE_PIN AF1 [get_ports {ddr3_dq[10]}]
set_property PACKAGE_PIN AE4 [get_ports {ddr3_dq[11]}]
set_property PACKAGE_PIN AE3 [get_ports {ddr3_dq[12]}]
set_property PACKAGE_PIN AE5 [get_ports {ddr3_dq[13]}]
set_property PACKAGE_PIN AF5 [get_ports {ddr3_dq[14]}]
set_property PACKAGE_PIN AF6 [get_ports {ddr3_dq[15]}]
set_property PACKAGE_PIN AJ4 [get_ports {ddr3_dq[16]}]
set_property PACKAGE_PIN AH6 [get_ports {ddr3_dq[17]}]
set_property PACKAGE_PIN AH5 [get_ports {ddr3_dq[18]}]
set_property PACKAGE_PIN AH2 [get_ports {ddr3_dq[19]}]
set_property PACKAGE_PIN AJ2 [get_ports {ddr3_dq[20]}]
set_property PACKAGE_PIN AJ1 [get_ports {ddr3_dq[21]}]
set_property PACKAGE_PIN AK1 [get_ports {ddr3_dq[22]}]
set_property PACKAGE_PIN AJ3 [get_ports {ddr3_dq[23]}]
set_property PACKAGE_PIN AF7 [get_ports {ddr3_dq[24]}]
set_property PACKAGE_PIN AG7 [get_ports {ddr3_dq[25]}]
set_property PACKAGE_PIN AJ6 [get_ports {ddr3_dq[26]}]
set_property PACKAGE_PIN AK6 [get_ports {ddr3_dq[27]}]
set_property PACKAGE_PIN AJ8 [get_ports {ddr3_dq[28]}]
set_property PACKAGE_PIN AK8 [get_ports {ddr3_dq[29]}]
set_property PACKAGE_PIN AK5 [get_ports {ddr3_dq[30]}]
set_property PACKAGE_PIN AK4 [get_ports {ddr3_dq[31]}]
set_property PACKAGE_PIN AD1 [get_ports {ddr3_dqs_n[0]}]
set_property PACKAGE_PIN AG3 [get_ports {ddr3_dqs_n[1]}]
set_property PACKAGE_PIN AH1 [get_ports {ddr3_dqs_n[2]}]
set_property PACKAGE_PIN AJ7 [get_ports {ddr3_dqs_n[3]}]
set_property PACKAGE_PIN AD2 [get_ports {ddr3_dqs_p[0]}]
set_property PACKAGE_PIN AG4 [get_ports {ddr3_dqs_p[1]}]
set_property PACKAGE_PIN AG2 [get_ports {ddr3_dqs_p[2]}]
set_property PACKAGE_PIN AH7 [get_ports {ddr3_dqs_p[3]}]
set_property PACKAGE_PIN AK9 [get_ports {ddr3_odt[0]}]
set_property PACKAGE_PIN AK9 [get_ports ddr3_odt]
set_property PACKAGE_PIN AE11 [get_ports ddr3_ras_n]
set_property PACKAGE_PIN AG5 [get_ports ddr3_reset_n]
set_property PACKAGE_PIN AG13 [get_ports ddr3_we_n]


# OpenXC7 timing constraints.
create_clock -name clk200 -period 5.000 [get_ports default_200mhz_clk_p]

set_false_path -from [get_ports resetn]
set_false_path -from [get_ports south_reset]

# Do not add SD generated-clock/input-delay guesses here yet. The current
# nextpnr report's limiting path is inside the CPUCLK domain, not the SD pins.
