// AXI4 to AXI4-Lite converter which preserves the AXI transfer-size encoding
// for a non-AXI-Lite downstream consumer (the AHB bridge in cvwsoc_ahb).
//
// AXI4-Lite has no AWSIZE or ARSIZE signals.  The PULP axi_to_axi_lite
// converter correctly splits bursts, but therefore cannot convey SIZE on its
// AXI-Lite interface.  This wrapper retains that converter unchanged and
// exports SIZE on two local, parallel wires.  They are not AXI-Lite signals.
//
// The wrapper deliberately supports one outstanding read and one outstanding
// write, matching the cvwsoc use case.  A burst has one AXI SIZE value, so the
// captured value remains valid for every AXI-Lite transaction generated by
// the converter's internal burst splitter until the final AXI response.
module axi_to_axi_lite_with_size #(
  parameter int unsigned AxiAddrWidth    = 32'd0,
  parameter int unsigned AxiDataWidth    = 32'd0,
  parameter int unsigned AxiIdWidth      = 32'd0,
  parameter int unsigned AxiUserWidth    = 32'd0,
  parameter int unsigned AxiMaxWriteTxns = 1,
  parameter int unsigned AxiMaxReadTxns  = 1,
  parameter bit          FullBW          = 0,
  parameter bit          FallThrough     = 1'b1,
  parameter type         full_req_t      = logic,
  parameter type         full_resp_t     = logic,
  parameter type         lite_req_t      = logic,
  parameter type         lite_resp_t     = logic
) (
  input  logic       clk_i,
  input  logic       rst_ni,
  input  logic       test_i,
  input  full_req_t  slv_req_i,
  output full_resp_t slv_resp_o,
  output lite_req_t  mst_req_o,
  input  lite_resp_t mst_resp_i,

  // Local metadata for the AXI-Lite-to-AHB bridge.  Valid whenever the
  // corresponding AXI-Lite address channel is valid.
  output logic [2:0] mst_awsize_o,
  output logic [2:0] mst_arsize_o
);

  logic [2:0] awsize_q, arsize_q;

  // Keep the original converter responsible for all AXI protocol work,
  // including splitting AXI bursts into individual AXI-Lite transactions.
  axi_to_axi_lite #(
    .AxiAddrWidth    ( AxiAddrWidth    ),
    .AxiDataWidth    ( AxiDataWidth    ),
    .AxiIdWidth      ( AxiIdWidth      ),
    .AxiUserWidth    ( AxiUserWidth    ),
    .AxiMaxWriteTxns ( AxiMaxWriteTxns ),
    .AxiMaxReadTxns  ( AxiMaxReadTxns  ),
    .FullBW          ( FullBW          ),
    .FallThrough     ( FallThrough     ),
    .full_req_t      ( full_req_t      ),
    .full_resp_t     ( full_resp_t     ),
    .lite_req_t      ( lite_req_t      ),
    .lite_resp_t     ( lite_resp_t     )
  ) i_axi_to_axi_lite (
    .clk_i, .rst_ni, .test_i,
    .slv_req_i, .slv_resp_o, .mst_req_o, .mst_resp_i
  );

  // A single AXI burst has one SIZE encoding.  Preserve it from the full AXI
  // address handshake through completion of that request.  The internal
  // burst splitter may emit several AXI-Lite address handshakes in between.
  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni) begin
      awsize_q <= '0;
      arsize_q <= '0;
    end else begin
      if (slv_req_i.aw_valid && slv_resp_o.aw_ready)
        awsize_q <= slv_req_i.aw.size;
      if (slv_req_i.ar_valid && slv_resp_o.ar_ready)
        arsize_q <= slv_req_i.ar.size;
    end
  end

  // Bypass the just-accepted request so a fall-through implementation of the
  // PULP converter cannot present its first AXI-Lite address with the
  // previous transaction's SIZE during that same clock cycle.
  assign mst_awsize_o = (slv_req_i.aw_valid && slv_resp_o.aw_ready) ?
                        slv_req_i.aw.size : awsize_q;
  assign mst_arsize_o = (slv_req_i.ar_valid && slv_resp_o.ar_ready) ?
                        slv_req_i.ar.size : arsize_q;

  // The size registers above are a single-entry association with the PULP
  // converter.  Multiple outstanding same-direction AXI requests would need
  // a matching FIFO of SIZE values, so reject that unsupported configuration.
  // pragma translate_off
  initial begin
    assert (AxiMaxWriteTxns == 1)
      else $fatal(1, "axi_to_axi_lite_with_size requires AxiMaxWriteTxns == 1");
    assert (AxiMaxReadTxns == 1)
      else $fatal(1, "axi_to_axi_lite_with_size requires AxiMaxReadTxns == 1");
  end
  // pragma translate_on

endmodule
